### ISSUE TITLE
BuildGroups.py error with DIAMOND 0.7.9

### ISSUE THREAD

**Issue by Bjartur108** [ryanmelnyk/PyParanoid#6]
I figured this issue out but it may be helpful for others to modify the documentation.

When I ran BuildGroups.py with the default settings, I got the following error:

> Traceback (most recent call last):
  File "/home/okra108/.conda/envs/pyparanoid/bin/BuildGroups.py", line 551, in <module>
    main()
  File "/home/okra108/.conda/envs/pyparanoid/bin/BuildGroups.py", line 516, in main
    parse_diamond(genes,strains)
  File "/home/okra108/.conda/envs/pyparanoid/bin/BuildGroups.py", line 113, in parse_diamond
    for line in open(os.path.join(outdir,"m8",s+".m8"),'r'):
IOError: [Errno 2] No such file or directory: '/home/okra108/Comp_Bif_genomes/Pangenomics/bif_pyp/m8/B_adolescentis_ATCC15703.m8'

Within bif_pyp, the .faa files were successfully formatted and placed in /faa,  but it appears that DIAMOND failed to generate .m8 files, and /m8 is empty (as are all other directories in bif_pyp). The script's output contained the following message:

> Formatting 28 fasta files...
Making diamond databases for 28 strains...
Running DIAMOND on all 28 strains...
        Done!
Getting gene lengths...
Parsing diamond results for 28 strains...

I was initially using DIAMOND 0.7.9. I installed the most recent version (0.9.22) and the script ran without issue. You may want to specify the required versions of your dependencies.

Best,
Nick

**Comment by ryanmelnyk** [comment]
thanks, will do
